export const PALETTES={
 SIGNAL:["TERMINAL_GREEN","PHOSPHOR_AMBER","DEAD_BLUE","STATIC_GREY","EMERGENCY_RED","NIGHT_VIOLET"],
 RELIC:["ARCHIVE_BEIGE","OXIDIZED_BRONZE","DUST_GREY","CEREMONIAL_RED","BONE_IVORY","MUSEUM_GREEN"],
 SPECIMEN:["MARSH_GREEN","TOXIC_LIME","MUD_BROWN","COLD_BLUE","PALE_FLESH","MOSS"],
 VESSEL:["ENAMEL_CREAM","COBALT","BOTTLE_GREEN","CLAY_RED","SMOKE","MILK_GLASS"],
 IMPLEMENT:["IRON","BRASS","RUST","WORKSHOP_BLUE","BLACKENED_STEEL","SAFETY_YELLOW"],
 WEAPON:["IRON","OBSIDIAN","OXIDIZED_BRONZE","BLOOD_RED","CEREMONIAL_GOLD","FROST"],
 REMAINS:["BONE","ASH","FOSSIL_BROWN","CHALK","PEAT","OLD_IVORY"],
 MACHINE:["INDUSTRIAL_GREY","CONTROL_GREEN","WARNING_ORANGE","BEIGE","BLACK","LAB_BLUE"]
};
